In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn import metrics
from scipy.stats import mode
from scipy.spatial import distance_matrix

In [ ]:
df = pd.read_csv("CreditPrediction.csv")

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df = df.drop_duplicates()

In [ ]:
df = df.drop(columns=['Unnamed: 19'])

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df['Gender'].value_counts()

In [ ]:
df['Education_Level'].value_counts()

In [ ]:
df['Marital_Status'].value_counts()

In [ ]:
df['Income_Category'].value_counts()

In [ ]:
df['Card_Category'].value_counts()

In [ ]:
df['Marital_Status'] = df['Marital_Status'].replace('Unknown', np.nan)
df['Education_Level'] = df['Education_Level'].replace('Unknown', np.nan)
df['Income_Category'] = df['Income_Category'].replace('Unknown', np.nan)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df

In [ ]:
df['Card_Category'] = df['Card_Category'].map({"Blue":0, "Silver":1, "Gold":2, "Platinum":3})

In [ ]:
df['Income_Category'] = df['Income_Category'].map({"Less than $40K":0, "$40K - $60K":1, "$60K - $80K":2 ,"$80K - $120K":3, "$120K +":4})

In [ ]:
df['Gender'] = df['Gender'].map({"M":0, "F":1})

In [ ]:
df['Education_Level'] = df['Education_Level'].map({"Uneducated":0, "High School":1, "College":2 ,"Graduate":3, "Post-Graduate":4, "Doctorate":5})

In [ ]:
df.info()

In [ ]:
df['Marital_Status'] = df['Marital_Status'].fillna('nan')
df = pd.get_dummies(df, columns=['Marital_Status'])
df.loc[df['Marital_Status_nan'] == 1, ['Marital_Status_Divorced', 'Marital_Status_Married', 'Marital_Status_Single']] = pd.NA

In [ ]:
df = df.drop(columns=['Marital_Status_nan'])

In [ ]:
df[['Marital_Status_Divorced', 'Marital_Status_Married', 'Marital_Status_Single']] = df[['Marital_Status_Divorced', 'Marital_Status_Married', 'Marital_Status_Single']].astype(float)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
eda = df.copy()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['CLIENTNUM'], bins=100, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Customer_Age'], bins=100, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
gender_labels = {0: 'Male', 1: 'Female'}
eda['Gender'] = eda['Gender'].map(gender_labels)
gender_counts = eda['Gender'].value_counts()

# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
gender_counts.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Dependent_count_counts = eda['Dependent_count'].value_counts()
Dependent_count_counts = Dependent_count_counts.sort_index()


# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
Dependent_count_counts.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Gender Distribution')
plt.xlabel('Dependent_count')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Education_Level_labels = {0: "Uneducated", 1: "High School", 2: "College", 3: "Graduate", 4: "Post-Graduate", 5: "Doctorate"}
eda['Education_Level'] = eda['Education_Level'].map(Education_Level_labels)
Education_Level_counts = eda['Education_Level'].value_counts()
Education_Level_counts_sorted = Education_Level_counts.reindex(Education_Level_labels.values())

# Plotting the bar plot
plt.figure(figsize=(10, 6))  # Adjust the figure size as needed
Education_Level_counts_sorted.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Education Level Distribution')
plt.xlabel('Education Level')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Income_Category_labels = {0:"Less than $40K", 1:"$40K - $60K", 2:"$60K - $80K" ,3:"$80K - $120K", 4:"$120K +"}
eda['Income_Category'] = eda['Income_Category'].map(Income_Category_labels)
Income_Category_counts = eda['Income_Category'].value_counts()
Income_Category_counts_sorted = Income_Category_counts.reindex(Income_Category_labels.values())

# Plotting the bar plot
plt.figure(figsize=(10, 6))  # Adjust the figure size as needed
Income_Category_counts_sorted.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Education Level Distribution')
plt.xlabel('Income_Category')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Card_Category_labels = {0:"Blue", 1:"Silver", 2:"Gold", 3:"Platinum"}
eda['Card_Category'] = eda['Card_Category'].map(Card_Category_labels)
Card_Category_counts = eda['Card_Category'].value_counts()
Card_Category_counts_sorted = Card_Category_counts.reindex(Card_Category_labels.values())

# Plotting the bar plot
plt.figure(figsize=(10, 6))  # Adjust the figure size as needed
Card_Category_counts_sorted.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Education Level Distribution')
plt.xlabel('Card_Category')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels if needed
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Months_on_book'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
Total_Relationship_Count = eda['Total_Relationship_Count'].value_counts()
Total_Relationship_Count = Dependent_count_counts.sort_index()


# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
Total_Relationship_Count.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Gender Distribution')
plt.xlabel('Dependent_count')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Months_Inactive_12_mon_Count = eda['Months_Inactive_12_mon'].value_counts()
Months_Inactive_12_mon_Count = Months_Inactive_12_mon_Count.sort_index()


# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
Months_Inactive_12_mon_Count.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Gender Distribution')
plt.xlabel('Dependent_count')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
Contacts_Count_12_mon_Count = eda['Contacts_Count_12_mon'].value_counts()
Contacts_Count_12_mon_Count = Contacts_Count_12_mon_Count.sort_index()


# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
Contacts_Count_12_mon_Count.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Gender Distribution')
plt.xlabel('Dependent_count')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Total_Revolving_Bal'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Total_Amt_Chng_Q4_Q1'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Total_Trans_Amt'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Total_Trans_Ct'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Total_Ct_Chng_Q4_Q1'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Avg_Utilization_Ratio'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
marital_status_counts = df[['Marital_Status_Divorced', 'Marital_Status_Married', 'Marital_Status_Single']].sum()

# Plotting the bar plot
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
marital_status_counts.plot(kind='bar', color='skyblue')  # Plotting the bar plot
plt.title('Bar Plot of Marital Status')
plt.xlabel('Marital Status')
plt.ylabel('Count')
plt.grid(axis='y')  # Add grid lines along the y-axis
plt.xticks(rotation=0)  # Rotate x-axis labels if needed
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))  # Adjust the figure size as needed
plt.hist(eda['Credit_Limit'], bins=50, color='skyblue', edgecolor='black')  # Adjust the number of bins as needed
plt.title('Histogram of Feature Column')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)  # Add grid lines
plt.show()

In [ ]:
df.info()

In [ ]:
pre = df.copy()
scaler = StandardScaler()
pre_scaled = pre.copy()
not_categoricals = ['CLIENTNUM', 'Customer_Age', 'Months_on_book',
        'Credit_Limit', 'Total_Revolving_Bal',
       'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct',
       'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']
for col in pre_scaled.columns:
    if col in not_categoricals:
        pre_scaled[col] = scaler.fit_transform(pre_scaled[[col]])

In [1804]:
df.corr()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,...,Credit_Limit,Total_Revolving_Bal,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single
CLIENTNUM,1.000000,0.006163,-0.020461,0.006681,-0.003527,0.023373,0.005162,0.132917,0.006979,0.005576,...,0.005696,0.000632,0.017336,-0.019552,-0.002532,0.008067,-0.000022,0.017214,-0.000364,-0.009015
Customer_Age,0.006163,1.000000,-0.003542,-0.078630,0.014884,0.029513,-0.007352,0.486908,-0.024827,0.032299,...,0.004239,0.005359,-0.049692,-0.020442,-0.027347,-0.009850,0.003514,-0.043451,0.012893,0.010626
Gender,-0.020461,-0.003542,1.000000,-0.007056,0.011211,-0.756882,-0.080131,0.008862,0.000093,0.010893,...,-0.423570,-0.030038,-0.028647,-0.027389,0.065958,0.003713,0.260809,0.004605,-0.022592,0.020373
Dependent_count,0.006681,-0.078630,-0.007056,1.000000,0.003872,0.069085,0.025704,-0.102680,-0.038637,-0.010848,...,0.068068,-0.002793,-0.035369,0.025035,0.049839,0.011040,-0.037195,0.013469,0.023038,-0.030677
Education_Level,-0.003527,0.014884,0.011211,0.003872,1.000000,-0.018957,0.008692,0.015306,-0.000888,-0.000480,...,-0.011965,-0.014539,-0.013859,-0.012009,-0.007660,-0.022011,-0.000334,-0.004397,0.016896,-0.014717
Income_Category,0.023373,0.029513,-0.756882,0.069085,-0.018957,1.000000,0.111036,0.016383,-0.007204,-0.018731,...,0.596036,0.040363,0.020352,0.026795,-0.053873,-0.006653,-0.316629,0.001402,0.026689,-0.027797
Card_Category,0.005162,-0.007352,-0.080131,0.025704,0.008692,0.111036,1.000000,-0.001733,-0.084926,-0.013033,...,0.449270,0.015571,0.007471,0.173602,0.118632,-0.004295,-0.182523,-0.016086,-0.037352,0.046602
Months_on_book,0.132917,0.486908,0.008862,-0.102680,0.015306,0.016383,-0.001733,1.000000,-0.009549,0.074901,...,0.007111,0.007692,-0.049190,-0.038340,-0.049902,-0.015111,-0.007882,-0.044017,0.026553,-0.002902
Total_Relationship_Count,0.006979,-0.024827,0.000093,-0.038637,-0.000888,-0.007204,-0.084926,-0.009549,1.000000,-0.004178,...,-0.071085,0.014216,0.051099,-0.346624,-0.240942,0.042053,0.067813,-0.003463,0.023659,-0.022076
Months_Inactive_12_mon,0.005576,0.032299,0.010893,-0.010848,-0.000480,-0.018731,-0.013033,0.074901,-0.004178,1.000000,...,-0.020253,-0.041634,-0.032333,-0.036963,-0.042811,-0.038930,-0.007129,-0.007226,-0.001163,0.005117
Contacts_Count_12_mon,0.005930,0.005839,-0.038633,-0.040455,-0.015772,0.028828,0.004323,-0.010066,0.055444,0.029274,...,0.020836,-0.054181,-0.024252,-0.112652,-0.151961,-0.094725,-0.055733,-0.006435,-0.010699,0.014345
Credit_Limit,0.005696,0.004239,-0.423570,0.068068,-0.011965,0.596036,0.449270,0.007111,-0.071085,-0.020253,...,1.000000,0.042590,0.012901,0.171779,0.075927,-0.001819,-0.482793,0.021244,-0.050330,0.039399
Total_Revolving_Bal,0.000632,0.005359,-0.030038,-0.002793,-0.014539,0.040363,0.015571,0.007692,0.014216,-0.041634,...,0.042590,1.000000,0.057919,0.064306,0.055927,0.089718,0.624136,-0.003308,0.042911,-0.041660
Total_Amt_Chng_Q4_Q1,0.017336,-0.049692,-0.028647,-0.035369,-0.013859,0.020352,0.007471,-0.049190,0.051099,-0.032333,...,0.012901,0.057919,1.000000,0.039849,0.005642,0.384378,0.035144,0.000658,0.045286,-0.046229
Total_Trans_Amt,-0.019552,-0.020442,-0.027389,0.025035,-0.012009,0.026795,0.173602,-0.038340,-0.346624,-0.036963,...,0.171779,0.064306,0.039849,1.000000,0.807159,0.085836,-0.083051,0.021691,-0.066508,0.055542
Total_Trans_Ct,-0.002532,-0.027347,0.065958,0.049839,-0.007660,-0.053873,0.118632,-0.049902,-0.240942,-0.042811,...,0.075927,0.055927,0.005642,0.807159,1.000000,0.112694,0.002700,0.037544,-0.134063,0.115326
Total_Ct_Chng_Q4_Q1,0.008067,-0.009850,0.003713,0.011040,-0.022011,-0.006653,-0.004295,-0.015111,0.042053,-0.038930,...,-0.001819,0.089718,0.384378,0.085836,0.112694,1.000000,0.074017,-0.008703,0.010848,-0.006244
Avg_Utilization_Ratio,-0.000022,0.003514,0.260809,-0.037195,-0.000334,-0.316629,-0.182523,-0.007882,0.067813,-0.007129,...,-0.482793,0.624136,0.035144,-0.083051,0.002700,0.074017,1.000000,-0.021910,0.047585,-0.036256
Marital_Status_Divorced,0.017214,-0.043451,0.004605,0.013469,-0.004397,0.001402,-0.016086,-0.044017,-0.003463,-0.007226,...,0.021244,-0.003308,0.000658,0.021691,0.037544,-0.008703,-0.021910,1.000000,-0.292568,-0.248758
Marital_Status_Married,-0.000364,0.012893,-0.022592,0.023038,0.016896,0.026689,-0.037352,0.026553,0.023659,-0.001163,...,-0.050330,0.042911,0.045286,-0.066508,-0.134063,0.010848,0.047585,-0.292568,1.000000,-0.853407
Marital_Status_Single,-0.009015,0.010626,0.020373,-0.030677,-0.014717,-0.027797,0.046602,-0.002902,-0.022076,0.005117,...,0.039399,-0.041660,-0.046229,0.055542,0.115326,-0.006244,-0.036256,-0.248758,-0.853407,1.000000

In [1825]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [1826]:
from sklearn.model_selection import train_test_split

# Assuming your DataFrame is called 'df' and the target variable is called 'Credit_Limit'
X = fin.drop(columns=['Credit_Limit'])  # Features
y = fin['Credit_Limit']                 # Target variable

# Splitting the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Optionally, you can further split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=42)

# Define the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1)  # No activation for output layer (linear activation by default)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val))

Epoch 1/50

/home/influx/.conda/envs/ML/lib/python3.10/site-packages/keras/src/layers/core/dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

228/228 ━━━━━━━━━━━━━━━━━━━━ 1s 889us/step - loss: 154307088.0000 - val_loss: 74177632.0000
Epoch 2/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - loss: 74285480.0000 - val_loss: 53517456.0000
Epoch 3/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 49952660.0000 - val_loss: 35140252.0000
Epoch 4/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - loss: 34577772.0000 - val_loss: 28475886.0000
Epoch 5/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 28472886.0000 - val_loss: 24512462.0000
Epoch 6/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - loss: 24930304.0000 - val_loss: 22613778.0000
Epoch 7/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step - loss: 23882662.0000 - val_loss: 21415198.0000
Epoch 8/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - loss: 20617998.0000 - val_loss: 20644958.0000
Epoch 9/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - loss: 22544248.0000 - val_loss: 20101422.0000
Epoch 10/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 20407954.0000 - val_loss: 19615616.0000
Epoch 11/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step - loss: 20533598.0000 - val_loss: 19216514.0000
Epoch 12/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - loss: 19751720.0000 - val_loss: 18934674.0000
Epoch 13/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 19507036.0000 - val_loss: 18810140.0000
Epoch 14/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 17822334.0000 - val_loss: 19344406.0000
Epoch 15/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 18177230.0000 - val_loss: 17988210.0000
Epoch 16/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - loss: 17763876.0000 - val_loss: 18280064.0000
Epoch 17/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step - loss: 17312374.0000 - val_loss: 17519100.0000
Epoch 18/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - loss: 17511902.0000 - val_loss: 17581038.0000
Epoch 19/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - loss: 18726270.0000 - val_loss: 17296244.0000
Epoch 20/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - loss: 17065130.0000 - val_loss: 17701084.0000
Epoch 21/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - loss: 17793078.0000 - val_loss: 17149562.0000
Epoch 22/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - loss: 15848785.0000 - val_loss: 16920196.0000
Epoch 23/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 16890920.0000 - val_loss: 16795932.0000
Epoch 24/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 17251048.0000 - val_loss: 16418729.0000
Epoch 25/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step - loss: 16229143.0000 - val_loss: 16320034.0000
Epoch 26/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - loss: 16453146.0000 - val_loss: 16093904.0000
Epoch 27/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - loss: 15084928.0000 - val_loss: 16043721.0000
Epoch 28/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 14878169.0000 - val_loss: 16546266.0000
Epoch 29/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - loss: 14782540.0000 - val_loss: 16381332.0000
Epoch 30/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - loss: 15042067.0000 - val_loss: 15670352.0000
Epoch 31/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 15475719.0000 - val_loss: 15550377.0000
Epoch 32/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - loss: 15287932.0000 - val_loss: 15539234.0000
Epoch 33/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - loss: 14422580.0000 - val_loss: 15268889.0000
Epoch 34/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - loss: 14156305.0000 - val_loss: 15492706.0000
Epoch 35/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - loss: 14171628.0000 - val_loss: 15204827.0000
Epoch 36/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - loss: 14509574.0000 - val_loss: 15100103.0000
Epoch 37/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - loss: 14535265.0000 - val_loss: 14587525.0000
Epoch 38/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 13886703.0000 - val_loss: 14853937.0000
Epoch 39/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - loss: 14155585.0000 - val_loss: 14251040.0000
Epoch 40/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 13381941.0000 - val_loss: 14084671.0000
Epoch 41/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - loss: 13577175.0000 - val_loss: 14121392.0000
Epoch 42/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - loss: 12689495.0000 - val_loss: 13609489.0000
Epoch 43/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 12525040.0000 - val_loss: 13669188.0000
Epoch 44/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 13157780.0000 - val_loss: 13175579.0000
Epoch 45/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - loss: 12627637.0000 - val_loss: 12961900.0000
Epoch 46/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 12264147.0000 - val_loss: 13294769.0000
Epoch 47/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - loss: 12074549.0000 - val_loss: 12574710.0000
Epoch 48/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - loss: 11742955.0000 - val_loss: 12303018.0000
Epoch 49/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - loss: 11786714.0000 - val_loss: 12222730.0000
Epoch 50/50
228/228 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - loss: 10806072.0000 - val_loss: 12005797.0000

In [1827]:
# Assuming you have already trained the model

# Predicting on the test set
y_pred = model.predict(X_test)

# If you want to evaluate the performance of your model, you can use appropriate metrics
from sklearn.metrics import mean_squared_error

# Calculate Mean Squared Error (MSE) between the predicted values and the actual values
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error on Test Set:", mse)

64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step
Mean Squared Error on Test Set: 11614874.268249802

In [1829]:
X_test

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Total_Revolving_Bal,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single
4344,-0.619550,0.313226,1.0,2,4.0,0.0,0.0,0.010987,3.0,3,3,-1.426724,-1.427405,-0.789290,-0.888760,-1.415920,-0.997166,0.0,1.0,0.0
3524,-0.593848,-0.203853,1.0,4,0.0,0.0,0.0,0.010987,3.0,2,0,1.108188,-1.354410,-0.192762,0.645101,-0.189586,-0.239004,1.0,0.0,0.0
4115,-0.617719,0.978041,1.0,1,3.0,0.0,0.0,0.010987,6.0,1,3,0.046862,0.046168,-0.072632,0.261636,-0.256782,-0.010467,0.0,0.0,1.0
7669,-0.759467,-0.203853,1.0,3,0.0,0.0,0.0,0.010987,5.0,3,1,-0.762936,0.278837,-0.067921,0.219029,1.998496,0.366800,0.0,0.0,1.0
4153,-0.561127,-0.351590,1.0,3,5.0,0.0,0.0,-2.263412,5.0,3,4,-1.426724,-2.212093,-0.883804,-1.144403,-1.688905,-0.997166,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3656,1.071086,-0.129985,0.0,3,1.0,3.0,0.0,-1.252568,3.0,2,2,-0.231659,0.443074,-0.184223,0.772923,-0.076192,-0.804905,0.0,1.0,0.0
4761,1.614706,-0.056116,1.0,4,1.0,3.0,0.0,0.516409,5.0,2,3,0.298390,0.912975,-0.209839,0.432065,-0.029994,-0.804905,1.0,0.0,0.0
5660,1.074508,0.239357,0.0,2,3.0,3.0,0.0,-0.620791,3.0,3,3,-1.032868,0.000546,-0.684765,-0.121829,-0.680959,-0.906477,0.0,1.0,0.0
6409,-0.603715,0.165489,0.0,4,5.0,1.0,0.0,0.390053,5.0,1,2,-1.426724,-0.902758,-0.209839,0.517279,-0.848950,-0.997166,0.0,1.0,0.0
343,-0.658725,0.830304,0.0,1,0.0,1.0,0.0,0.010987,2.0,4,3,-0.767843,0.269713,-1.086082,-2.209584,-2.226476,0.355917,0.0,1.0,0.0

In [ ]:
### Assuming you have already trained the model

# Predicting on the test set
y_pred = model.predict(X_test)

# If you want to evaluate the performance of your model, you can use appropriate metrics
from sklearn.metrics import mean_squared_error

# Calculate Mean Squared Error (MSE) between the predicted values and the actual values
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error on Test Set:", mse)

In [ ]:
missing_Income_Category = pre_scaled[pre_scaled['Total_Relationship_Count'].isna()]
cnt = 0
for index, row in missing_Income_Category.iterrows():
    neighbors = []
    for indexN, rowN in complete_rows.iterrows():
        distance = euclidean_distance(row, rowN, exclude_columns=['Total_Relationship_Count'])
        neighbors.append((indexN, distance))
    neighbors.sort(key=lambda x: x[1])
    K = 11
    nearest_neighbors_indices = [neighbor[0] for neighbor in neighbors[:K]]

    # Get the 'Gender' values of the K nearest neighbors
    nearest_genders = df.loc[nearest_neighbors_indices, 'Total_Relationship_Count']

    # Calculate the mode of the 'Gender' values
    most_common_gender = mode(nearest_genders).mode

    # Update the 'Gender' value of the current row
    df.at[index, 'Total_Relationship_Count'] = most_common_gender
    cnt += 1
    if cnt % 100 == 0:
        print(f"Index: {index}, Imputed Gender: {most_common_gender}")